filter_type: UKF                                           # The Kalman filter type, EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
cv_noise_params:                                           # The noise for the constant velocity prediction model
    x: 0.001
    y: 0.001
    z: 0.001
detectors:                                                 # Add detectors under this namespace
    upper_body:                                            # Name of detector (used internally to identify them). Has to be unique.
        topic: "localized_objects"                         # The topic on which the detections are published
        cartesian_noise_params:                            # The noise for the cartesian observation model
            x: 0.5
            y: 0.5
            z: 0.5
        matching_algorithm: "NNJPDA"                       # The algorithm to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
detection_sampling_radius: 0.5
maximum_detection_distance: 4.0 # TODO use this parameter
