filter_type: UKF                                           # The Kalman filter type, EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
prediction_type: CV                                        # The prediction model type, CV = Constant velocity, S = Static (velocity = 0) TODO add decreasing velocity model, free fall just for fun
cv_noise_params:                                           # The noise for the constant velocity prediction model. Required if prediction_type: CV
    x: 0.0001
    y: 0.0001
    z: 0.0001
detectors:                                                 # Add detectors under this namespace
    upper_body:                                            # Name of detector (used internally to identify them). Has to be unique.
        topic: "localized_objects"                         # The topic on which the detections are published
        cartesian_noise_params:                            # The noise for the cartesian observation model
            x: 0.05
            y: 0.05
            z: 0.05
        matching_algorithm: "NNJPDA"                       # The algorithm to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
detection_sampling_radius: 0.25
maximum_detection_distance: 2.0 # TODO use this parameter