filter_type: UKF                       # The Kalman filter type, EKF = Extended Kalman Filter, UKF = Uncented Kalman Filter
prediction_type: S                     # The prediction model type, CV = Constant velocity, S = Static (velocity = 0) TODO add decreasing velocity model, free fall just for fun
cv_noise_params:                       # The noise for the constant velocity prediction model. Required if prediction_type: CV
    x: 0.0001
    y: 0.0001
    z: 0.0001
sequence_size: 3                       # Minimum number of unmatched observations to create new track hypothesis from a sequence. Must be greater than 0.
sequence_time: 4.0                     # Time before a sequence is invalidated unless observations are matched to it. Must be greater than 0.0.
detectors:                             # Add detectors under this namespace
    upper_body:                        # Name of detector (used internally to identify them). Has to be unique.
        topic: "specific_localizer/localized_objects"     # The topic on which the detections are published
        cartesian_noise_params:        # The noise for the cartesian observation model
            x: 0.2
            y: 0.2
            z: 0.2
        matching_algorithm: NNJPDA_LABELED         # The algorithm to match different detections. NN = Nearest Neighbour, NNJPDA = NN Joint Probability Data Association
detection_sampling_radius: 0.15
maximum_detection_distance: 2.0 # TODO use this parameter

print_debug_info: false
